[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
FunctionImplementations = "7c7cc465-9c6a-495f-bdd1-f42428e86d0c"

[sources]
FunctionImplementations = {path = ".."}

[compat]
Documenter = "1"
Literate = "2"
FunctionImplementations = "0.4"
